/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class", '[data-theme="dark"]'],
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: "#5e6ad2",
          bg: "#5e6ad2",
          text: "#ffffff",
          accent: "#7170ff",
          hover: "#828fff",
          tint: "#18182f",
          indigo: "#5e6ad2",
          link: "#828fff",
        },
        surface: {
          DEFAULT: "var(--color-bg-translucent)",
          base: "var(--bg-base)",
          card: "var(--surface-card)",
          elevated: "var(--surface-elevated)",
          secondary: "var(--color-bg-secondary)",
          tertiary: "var(--color-bg-tertiary)",
          quaternary: "var(--color-bg-quaternary)",
          panel: "var(--color-bg-panel)",
          tint: "var(--surface-tint)",
          "tint-hover": "var(--surface-tint-hover)",
          "tint-strong": "var(--surface-tint-strong)",
          rail: "var(--glass-rail)",
          level0: "var(--color-bg-level-0)",
          level1: "var(--color-bg-level-1)",
          level2: "var(--color-bg-level-2)",
          level3: "var(--color-bg-level-3)",
          shade: "var(--surface-elevated)",
          marketing: "var(--color-bg-marketing)",
          translucent: "var(--color-bg-translucent)",
          header: "var(--header-bg)",
        },
        border: {
          DEFAULT: "var(--color-border-primary)",
          subtle: "var(--border-subtle)",
          strong: "var(--border-strong)",
          primary: "var(--color-border-primary)",
          secondary: "var(--color-border-secondary)",
          tertiary: "var(--color-border-tertiary)",
          thin: "var(--color-border-primary)",
          solid: "var(--color-border-secondary)",
          faint: "var(--border-subtle)",
          header: "var(--header-border)",
        },
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          tertiary: "var(--color-text-tertiary)",
          quaternary: "var(--color-text-quaternary)",
          label: "var(--color-text-primary)",
          faint: "var(--color-text-quaternary)",
        },
        status: {
          green: "#27a644",
          emerald: "#27a644",
          red: "#eb5757",
          orange: "#fc7840",
          yellow: "#f0bf00",
          teal: "#00b8cc",
          blue: "#4ea7fc",
        },
      },
      fontFamily: {
        display: [
          "Plus Jakarta Sans",
          "Geist",
          "SF Pro Display",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        sans: [
          "Geist",
          "Plus Jakarta Sans",
          "SF Pro Display",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Oxygen",
          "Ubuntu",
          "Cantarell",
          "Open Sans",
          "Helvetica Neue",
          "sans-serif",
        ],
        mono: ["JetBrains Mono", "ui-monospace", "SF Mono", "Menlo", "monospace"],
      },
      fontSize: {
        tiny: ["0.625rem", { lineHeight: "1.5", letterSpacing: "-0.015em" }],
        micro: ["0.75rem", { lineHeight: "1.4", letterSpacing: "0em" }],
        mini: ["0.8125rem", { lineHeight: "1.5", letterSpacing: "-0.01em" }],
        small: ["0.875rem", { lineHeight: "calc(21 / 14)", letterSpacing: "-0.013em" }],
        regular: ["1rem", { lineHeight: "1.6", letterSpacing: "0em" }],
        large: ["1.125rem", { lineHeight: "1.6", letterSpacing: "-0.01em" }],
        title1: ["1.0625rem", { lineHeight: "1.4", letterSpacing: "-0.012em" }],
        title2: ["1.25rem", { lineHeight: "1.33", letterSpacing: "-0.012em" }],
        title3: ["1.5rem", { lineHeight: "1.33", letterSpacing: "-0.012em" }],
        title4: ["2rem", { lineHeight: "1.125", letterSpacing: "-0.022em" }],
        title5: ["2.5rem", { lineHeight: "1.1", letterSpacing: "-0.022em" }],
        title6: ["3rem", { lineHeight: "1", letterSpacing: "-0.022em" }],
        title7: ["3.5rem", { lineHeight: "1.1", letterSpacing: "-0.022em" }],
        title8: ["4rem", { lineHeight: "1.06", letterSpacing: "-0.022em" }],
        title9: ["4.5rem", { lineHeight: "1", letterSpacing: "-0.022em" }],
      },
      fontWeight: {
        light: "300",
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
      borderRadius: {
        4: "4px",
        6: "6px",
        8: "8px",
        12: "12px",
        14: "14px",
        16: "16px",
      },
      boxShadow: {
        low: "0px 2px 4px #0000001a",
        medium: "0px 4px 24px #0003",
        high: "0px 7px 32px #00000059",
        "stack-low":
          "0px 8px 2px 0px #0000, 0px 5px 2px 0px #00000003, 0px 3px 2px 0px #0000000a, 0px 1px 1px 0px #00000012, 0px 0px 1px 0px #00000014",
        modal:
          "0 4px 40px #0000001a, 0 3px 20px #00000020, 0 3px 12px #00000020, 0 2px 8px #00000020, 0 1px 1px #00000020",
        "card-glow": "0 0 0 1px #ffffff14, 0 8px 32px #08090a",
        invert:
          "inset 0 0 0 1px #ffffff08, inset 0 1px #ffffff0a, 0 0 0 1px #0009, 0 4px 4px #0000001a",
      },
      maxWidth: {
        page: "1024px",
        homepage: "1344px",
        prose: "624px",
      },
      transitionTimingFunction: {
        "out-quad": "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        "out-quint": "cubic-bezier(0.23, 1, 0.32, 1)",
      },
      keyframes: {
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        scaleIn: {
          from: { opacity: "0", transform: "translateX(-50%) scale(0.96)" },
          to: { opacity: "1", transform: "translateX(-50%) scale(1)" },
        },
        caret: {
          "0%, 49%": { opacity: "1" },
          "50%, 100%": { opacity: "0" },
        },
      },
      animation: {
        fadeIn: "fadeIn 0.175s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        scaleIn: "scaleIn 0.175s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        caret: "caret 1.1s steps(1) infinite",
      },
    },
  },
  plugins: [],
};
